version: '2'

services:
  django:
    build: .
    entrypoint: /bin/sh -c "python manage.py makemigrations && python manage.py createcachetable && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      MYSQL_DATABASE: ipredict
      MYSQL_USER: root
      MYSQL_PASSWORD: rooter
      MYSQL_HOST: mysql
      HOSTNAME_ALLOWED: "*"
      SPACES_ACCESS_ID: DO00UKVU2DWPQRBWMGKJ
      SPACES_SECRET_KEY: lZsnYEp/oyNoq+HVOAo8Nhy9ntwYKYb5tdrtzm894Zc
      REDIS_CONNECTION_STRING: redis://redis:6379
    ports:
      - '8000:8000'
    volumes:
      - './:/app:rw'
    links:
    - mysql:mysql
    - redis:redis
    networks:
    - tuxnet
    depends_on:
    - mysql
    - redis
    - rethinkdb
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rooter
      MYSQL_DATABASE: ipredict
      MYSQL_USER: ipredict
      MYSQL_PASSWORD: ipredict
    volumes:
    - './data:/var/lib/mysql'
    networks:
    - tuxnet
  worker:
    build: .
    entrypoint: /bin/sh -c "celery -A {{cookiecutter.project_slug}}.celery_app worker --loglevel=INFO --concurrency=8 -O fair -P prefork -n cel_app_worker"
    environment:
      MYSQL_DATABASE: ipredict
      MYSQL_USER: root
      MYSQL_PASSWORD: rooter
      MYSQL_HOST: mysql
      SPACES_ACCESS_ID: DO00UKVU2DWPQRBWMGKJ
      SPACES_SECRET_KEY: lZsnYEp/oyNoq+HVOAo8Nhy9ntwYKYb5tdrtzm894Zc
      REDIS_CONNECTION_STRING: redis://redis:6379
    volumes:
      - './:/app:rw'
    links:
      - mysql:mysql
      - redis:redis
    ports:
      - 5555:5555
    networks:
    - tuxnet
    depends_on:
    - mysql
    - redis
    - rethinkdb
  redis:
    image: redis:7.0
    ports:
    - 6379
    networks:
    - tuxnet
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
    - tuxnet
    depends_on:
    - django
    - redis
    - worker
    - mysql
    - frontend
    - rethinkdb
  frontend:
    build: ../{{cookiecutter.project_slug}}-ui
    volumes:
      - '../{{cookiecutter.project_slug}}-ui/build:/usr/share/nginx/html'
    links:
      - mysql:mysql
      - redis:redis
      - django:django
    networks:
    - tuxnet
    depends_on:
    - mysql
    - redis
    - rethinkdb
  rethinkdb:
    image: rethinkdb:2.4.2
    ports:
    - 8080:8080
    - 29015
    - 28015
    networks:
    - tuxnet

networks:
  tuxnet:
