FROM python:3.10.8-slim-bullseye
WORKDIR /app
RUN apt-get update \
      && apt-get -y install python3-dev  gcc musl-dev \
      build-essential \
      libffi-dev \
      mariadb-dev
COPY . /app
COPY certs/ca-certificate.crt /etc/certs/
RUN pip install -r requirements/prod.txt
RUN pip install sqlalchemy flower
RUN chmod +x /app/entrypoint.sh \
      && chmod +x /app/celery.sh
RUN useradd -ms /bin/sh appuser
USER appuser
CMD [ "/app/celery.sh" ]