version: '2'

services:
  django:
    build: .
    entrypoint: /bin/sh -c "python manage.py makemigrations && python manage.py createcachetable && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DATABASE: {{ cookiecutter.project_slug }}
      POSTGRES_USER: {{cookiecutter.project_slug}}
      POSTGRES_PASSWORD: {{cookiecutter.project_slug}}pw
      POSTGRES_HOST: postgres
      HOSTNAME_ALLOWED: "*"
      SPACES_ACCESS_ID: DO00UKVU2DWPQRBWMGKJ
      SPACES_SECRET_KEY: lZsnYEp/oyNoq+HVOAo8Nhy9ntwYKYb5tdrtzm894Zc
      REDIS_CONNECTION_STRING: redis://redis:6379
    ports:
      - '8000:8000'
    volumes:
      - './:/app:rw'
    links:
    - postgres:postgres
    - redis:redis
    networks:
    - tuxnet
    depends_on:
    - postgres
    - redis
    - rethinkdb
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}
      - POSTGRES_PASSWORD={{cookiecutter.project_slug}}pw
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
    networks:
    - tuxnet
  worker:
    build: .
    entrypoint: /bin/sh -c "celery -A {{cookiecutter.project_slug}}.celery_app worker --loglevel=INFO --concurrency=8 -O fair -P prefork -n cel_app_worker"
    environment:
      POSTGRES_DATABASE: {{ cookiecutter.project_slug }}
      POSTGRES_USER: {{cookiecutter.project_slug}}
      POSTGRES_PASSWORD: {{cookiecutter.project_slug}}pw
      POSTGRES_HOST: postgres
      SPACES_ACCESS_ID: DO00UKVU2DWPQRBWMGKJ
      SPACES_SECRET_KEY: lZsnYEp/oyNoq+HVOAo8Nhy9ntwYKYb5tdrtzm894Zc
      REDIS_CONNECTION_STRING: redis://redis:6379
    volumes:
      - './:/app:rw'
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - 5555:5555
    networks:
    - tuxnet
    depends_on:
    - postgres
    - redis
    - rethinkdb
  redis:
    image: redis:7.0
    ports:
    - 6379
    networks:
    - tuxnet
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
    - tuxnet
    depends_on:
    - django
    - redis
    - worker
    - postgres
    - rethinkdb
  rethinkdb:
    image: rethinkdb:2.4.2
    ports:
    - 8080:8080
    - 29015
    - 28015
    networks:
    - tuxnet

networks:
  tuxnet:
