apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "deploy.configname" . }}
data:
  postgres_db: "{{ .Values.database.name  }}"
  postgres_username: "{{ .Values.database.username }}"
  postgres_password: "{{ .Values.database.password }}"
  postgres_port: "{{ .Values.database.port }}"
  postgres_host: "{{ .Values.database.host }}"
  spaces_access_id: "{{ .Values.spaces.access_id }}"
  spaces_access_key: "{{ .Values.spaces.access_key }}"
  redis_connection_string: "{{ .Values.cache.redis_connection_string }}"
  serving_version: "{{ .Values.ml.serving_version }}"
  rdb_host: "{{ .Values.rdb.host }}"
  rdb_port: "{{ .Values.rdb.port }}"