{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: {{cookiecutter.project_slug}}
metadata:
  name: {{ include "deploy.serviceAccountName" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
