apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.appLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{cookiecutter.project_slug}}port
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
